[repository.alistral]
path = "./"
remote_url = "https://github.com/RustyNova016/Alistral"

    [repository.alistral.rust]
    fmt = true
    sqlx = false
    clippy_hack = false

# [repository.sequelles]
# path = "./sequelles"
# remote_url = "https://github.com/RustyNova016/sequelles"

#     [repository.sequelles.rust]
#     fmt = true
#     sqlx = false
#     clippy_hack = true