use interzic::models::messy_recording::MessyRecording;
use interzic::models::playlist_stub::PlaylistStub;
use itertools::Itertools as _;
use musicbrainz_db_lite::Recording;
use snafu::ResultExt as _;
use tracing::Span;
use tracing::instrument;
use tracing_indicatif::span_ext::IndicatifSpanExt as _;
use yumako_jams::YumakoClient;
use yumako_jams::models::radio_stream::radio_item::RadioItem;

use crate::ALISTRAL_CLIENT;
use crate::models::cli::radio::RadioExportTarget;
use crate::models::data_storage::DataStorage;
use crate::tools::yumako_jam::run::error::PlaylistConvertSnafu;
use crate::tools::yumako_jam::run::error::YumakoRunCommandError;
use crate::utils::data_file::DataFile as _;

#[expect(clippy::too_many_arguments, reason = "Interzic needs a full refactor")]
pub(super) async fn export_radio(
    conn: &mut sqlx::SqliteConnection,
    radio_name: &str,
    radio_desc: &str,
    radio_items: Vec<RadioItem>,
    target: RadioExportTarget,
    username: Option<String>,
    token: Option<&str>,
    instance: Option<&str>,
) -> Result<(), YumakoRunCommandError> {
    let playlist = radio_to_playlist(conn, radio_name, radio_desc, radio_items).await?;

    target
        .export(playlist, username, token, instance)
        .await
        .unwrap();

    Ok(())
}

async fn radio_to_playlist(
    conn: &mut sqlx::SqliteConnection,
    radio_name: &str,
    radio_desc: &str,
    radio_items: Vec<RadioItem>,
) -> Result<PlaylistStub, YumakoRunCommandError> {
    let counter = DataStorage::load().expect("Couldn't load data storage");

    Ok(PlaylistStub {
        title: format!(
            "Radio: {} #{}",
            radio_name,
            counter.write().unwrap().incr_playlist_count()
        ),
        description: format!(
            "{}\n\nGenerated by yumako_jams v{} (https://github.com/RustyNova016/Alistral)",
            radio_desc,
            YumakoClient::VERSION
        ),
        recordings: convert_recordings(
            conn,
            radio_items
                .into_iter()
                .map(|t| t.entity().clone())
                .collect_vec(),
        )
        .await?,
    })
}

#[instrument(skip_all, fields(indicatif.pb_show = tracing::field::Empty))]
async fn convert_recordings(
    db_lite_conn: &mut sqlx::SqliteConnection,
    recordings: Vec<Recording>,
) -> Result<Vec<MessyRecording>, YumakoRunCommandError> {
    Span::current().pb_set_length(recordings.len() as u64);
    Span::current().pb_set_message("Saving playlists recordings");

    let mut messy = Vec::new();

    for recording in recordings {
        let rec =
            MessyRecording::from_db_recording(db_lite_conn, &ALISTRAL_CLIENT.interzic, recording)
                .await
                .context(PlaylistConvertSnafu)?;

        let rec = rec
            .upsert(&ALISTRAL_CLIENT.interzic.database_client)
            .await
            .context(PlaylistConvertSnafu)?;

        messy.push(rec);
        Span::current().pb_inc(1);
    }

    Ok(messy)
}
