use chrono::Duration;
use futures::StreamExt;
use futures::stream;
use interzic::models::playlist_stub::PlaylistStub;
use tracing::info;

use crate::ALISTRAL_CLIENT;
use crate::datastructures::radio::collector::RadioCollector;
use crate::datastructures::radio::filters::cooldown::cooldown_filter;
use crate::datastructures::radio::filters::min_listens::min_listen_filter;
use crate::datastructures::radio::filters::timeouts::timeout_filter;
use crate::datastructures::radio::seeders::listens::ListenSeeder;
use crate::datastructures::radio::sorters::listen_rate::listen_rate_sorter;
use crate::models::cli::radio::RadioExportTarget;
use crate::models::data_storage::DataStorage;
use crate::models::error::ResultTEExt as _;
use crate::tools::radio::convert_recordings;
use crate::utils::data_file::DataFile as _;

pub async fn listen_rate_radio(
    seeder: ListenSeeder,
    token: &str,
    min_listens: Option<u64>,
    cooldown: u64,
    collector: RadioCollector,
    target: RadioExportTarget,
    client_name: &str,
) -> Result<(), crate::Error> {
    let username = seeder.username().clone();
    let conn = &mut *ALISTRAL_CLIENT.get_conn().await;

    info!("[Seeding] Getting listens");
    let recordings = seeder
        .seed(conn)
        .await
        .expect_fatal("Couldn't find seed listens");

    info!("[Filter] Filtering minimum listen count");
    let recordings = min_listen_filter(recordings.into_stream(), min_listens.unwrap_or(3));

    info!("[Filter] Filtering listen cooldown");
    let recordings = cooldown_filter(recordings, Duration::hours(cooldown as i64));

    info!("[Filter] Filtering listen timeouts");
    let recordings = timeout_filter(recordings);

    info!("[Sorting] Sorting listen by listen rate duration");
    let recordings = listen_rate_sorter(recordings.collect().await);

    info!("[Finalising] Creating radio playlist");
    let collected = collector
        .collect(stream::iter(recordings).map(|r| r.recording().clone()))
        .await;

    info!("[Sending] Sending radio playlist to listenbrainz");

    let counter = DataStorage::load().expect_fatal("Couldn't load data storage");
    let playlist = PlaylistStub {
        title: format!(
            "Radio: Listen Rate #{}",
            counter.write().unwrap().incr_playlist_count()
        ),
        description: "Automatically generated by: https://github.com/RustyNova016/Alistral"
            .to_string(),
        recordings: convert_recordings(conn, collected)
            .await
            .expect_fatal("Couldn't convert recordings for playlist"),
    };

    target
        .export(playlist, Some(username), Some(token), client_name)
        .await
        .expect_fatal("Couldn't send the playlist");

    Ok(())
}
