[package]
name = "musicbrainz-db-lite"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
musicbrainz_db_lite_macros = { path = "./musicbrainz_db_lite_macros" }
musicbrainz_db_lite_schema = { path = "./musicbrainz_db_lite_schema" }
tuillez = { path = "../tuillez", optional = true }

#musicbrainz_rs_nova = { version = "0.9.0", package = "musicbrainz_rs"  }
musicbrainz_rs_nova = { branch = "develop", git = "https://github.com/RustyNova016/musicbrainz_rs.git", package = "musicbrainz_rs" }
#musicbrainz_rs_nova = { path = "../musicbrainz_rs_nova" }

#listenbrainz = "0.8.1"
listenbrainz = { branch = "alistral_version", git = "https://github.com/RustyNova016/listenbrainz-rs.git", default-features = false, features = ["tls-native"] }

async-trait = "0.1.87"
chrono = "0.4.40"
extend = "1.2.0"
futures = "0.3.30"
macon = "1.2.0"
serde_json = "1.0.140"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "macros", "sqlite"] }
thiserror = "2.0.3"
tracing = "0.1.40"
itertools = "0.13.0"
serde = "1.0.210"
async-fn-stream = "0.2.2"
const_format = { version = "0.2.34" , features = ["rust_1_51", "rust_1_64", "assertcp"] }
tokio = { version = "1.40.0", features = ["full"] }

owo-colors = { version = "4.2.0", optional = true}
deadpool = "0.12.2"
reqwest = { version = "0.12.12", features = ["json"] }
streamies = "0.1.1"
governor = "0.8.1"

[features]
default = ["timeout_continue", "pretty_format"]
timeout_continue = []
pretty_format = ["dep:tuillez", "dep:owo-colors"]

[dev-dependencies]
serial_test = "3.1.1"

# [workspace]
# default-members = [
#     ".",
#     "musicbrainz_db_lite_schema",
#     "musicbrainz_db_lite_macros",
# ]
# members = ["musicbrainz_db_lite_schema", "musicbrainz_db_lite_macros"]
