[package]
name = "yumako_jams"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.0"

[dependencies]
alistral_core = { path = "../alistral_core" }
musicbrainz-db-lite = { path = "../musicbrainz_db_lite" }
tuillez = "0.1.0"

# Async
async-fn-stream = "0.3.2"
streamies = "0.2.2"
futures = "0.3.34"

# Debug
tracing = "0.1.44"

# Macros
extend = "1.2.0"
thiserror = "2.0.20"
snafu = "0.9.0"

# Utils
priority-queue = "2.3.0"
rust_decimal = "1.36.0"
itertools = "0.15.0"
serde = "1.0.229"
serde_json = "1.0.151"
json5 = "1.3.1"
chrono = "0.4.45"

[lints.clippy]
result_large_err = { level = "allow", priority = 1 }

[patch.crates-io]
sequelles = {git = "https://github.com/RustyNova016/sequelles", rev = "04918eda92d0602852cc50bb761da990159b6ff4"}
tuillez = {git = "https://github.com/RustyNova016/tuillez", rev = "debb79bf8c8656a4eedb571177a8ffa3b9984e78"}
musicbrainz_rs = {git = "https://github.com/RustyNova016/musicbrainz_rs", rev = "4e4e2b934940030027ede134e35dfd922ac6ca0e"}
listenbrainz_rs = { git = "https://github.com/RustyNova016/listenbrainz_rs", rev = "5ba127b377c0acd2c3169e73a3f849371bcf595e" }
submarine = { git = "https://github.com/eppixx/submarine", rev = "6a9b0a929bacff1fd89b7b0dddd44ff906f1d666" }
zip = { git = "https://github.com/RustyNova016/zip2", rev=  "4ebae293241d41249f3dd2283e9cc98899d42e33" }
