[package]
name = "youtube_brainz"
version = "0.1.0"
edition = "2021"
description = "Bunch of utilities to link metabrainz data to youtube"

[dependencies]
google-youtube3 = "6.0.0"
musicbrainz_rs = "0.9.0"
sqlx = "0.8.3"
thiserror = "2.0.0"
