name: release
on: [push]

      
jobs:
      get-tag:
            name: Get Release Tag
            runs-on: ubuntu-latest
            outputs:
                  tag: ${{ steps.get-latest-tag.outputs.tag }}
            steps:
                  - uses: actions/checkout@v4
                  
                  - uses: actions-ecosystem/action-get-latest-tag@v1
                    id: get-latest-tag

      release-linux:
            name: Create Release Linux
            runs-on: ubuntu-latest
            strategy:
                  fail-fast: false
            needs: get-tag
            steps:
                  - uses: actions/checkout@v4

                  - name: Install toolchain
                    uses: actions-rs/toolchain@v1
                    with:
                        toolchain: stable
                        override: true

                  - name: Build
                    run: cargo build --all --release
        
                  - name: Release
                    uses: softprops/action-gh-release@v2
                    with:
                      files: target/release/listenbrainz-cli-tools
                      tag_name: ${{needs.get-tag.outputs.tag}}
                    env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      release-windows:
            name: Create Release Windows
            runs-on: windows-latest
            strategy:
                  fail-fast: false
            needs: get-tag
            steps:
                  - uses: actions/checkout@v4

                  - name: Install toolchain
                    uses: actions-rs/toolchain@v1
                    with:
                      toolchain: stable
                      override: true

                  - name: Build
                    run: cargo build --all --release    
        
                  - name: Release
                    uses: softprops/action-gh-release@v2
                    with:
                         files: target/release/listenbrainz-cli-tools.exe
                         tag_name: ${{needs.get-tag.outputs.tag}}
                    env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

