name: release
on: [push]

      
jobs:
  release-linux:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --all --release

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/listenbrainz-cli-tools
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    name: Create Release Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --all --release --target x86_64-pc-windows-gnu      

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
                   files: target/release/listenbrainz-cli-tools.exe
                   tag_name: ${{ steps.get-latest-tag.outputs.tag }}
        env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
