name: Rust

on:
  pull_request:
    branches: [ "master*", "develop", "develop*" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  checks:
    env: 
      SQLX_OFFLINE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pre-build devShell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default

      - uses: Swatinem/rust-cache@v2

      # ====================
      #       Fmt
      # ====================

      - name: Run rustfmt
        id: rustfmt
        continue-on-error: true
        run: cargo fmt --all --check | ansi2html -i | tee rustfmt-output.txt

      # ====================
      #       Clippy
      # ====================

      - name: Run clippy all features
        id: clippy
        continue-on-error: true
        shell: 'nix develop -c bash -e {0}'
        run: cargo clippy --all-features -- -D warnings 2>&1 | tee clippy-output.txt

      # # ====================
      # #       Docs
      # # ====================

      # - name: Documentation
      #   id: docs
      #   continue-on-error: true
      #   env:
      #     RUSTDOCFLAGS: -Dwarnings
      #   run: cargo doc --all-features --no-deps --document-private-items 2>&1 | tee docs-output.txt

      # # ====================
      # #     MSRV Check
      # # ====================

      # - name: Run cargo-msrv
      #   id: msrv
      #   continue-on-error: true
      #   run: /bin/bash ./scripts/ci/msrv.sh 2>&1 | tee msrv-output.txt

      # # ====================
      # #    Useless deps
      # # ====================

      # - name: Run cargo-machete
      #   id: dependancies
      #   continue-on-error: true
      #   run: /bin/bash ./scripts/ci/udeps.sh 2>&1 | tee dependancies-output.txt

      # # ====================
      # #    Min versions
      # # ====================

      # - name: Install nightly toolchain for minimum_versions
      #   uses: dtolnay/rust-toolchain@nightly

      # - uses: taiki-e/install-action@cargo-hack

      # - uses: taiki-e/install-action@cargo-minimal-versions

      # - name: Run cargo-minimal-versions
      #   id: minimum_versions
      #   continue-on-error: true
      #   run: /bin/bash ./scripts/ci/minimum_versions.sh 2>&1 | tee minimum-versions-output.txt


      - uses: actions/github-script@v9
        with:
          script: |
            const script = require('./path/to/script.js')
            script({github, context})

  stable_tests:
    env: 
      SQLX_OFFLINE: true
    runs-on: ${{ matrix.os }}
    needs: checks
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2
        with: 
          key: "(${{ matrix.os }})"

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
        
      - name: Run tests
        run: cargo nextest run --all-features