name: Rust

on:
  pull_request:
    branches: [ "master*", "develop", "develop*" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  checks:
    env: 
      SQLX_OFFLINE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 1G
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago
          purge-created: 0
          # or last accessed this duration (ISO 8601 duration format)
          # before the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: P1DT12H
          # except any version with the key that is the same as the `primary-key`
          purge-primary-key: never

      - name: Pre-build devShell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default

      - uses: Swatinem/rust-cache@v2

      # ====================
      #       Fmt
      # ====================

      - name: Run rustfmt
        id: rustfmt
        continue-on-error: true
        shell: 'nix develop --impure -c bash -e {0}'
        run: cargo --color fmt --all --check | ansi2html -i | tee rustfmt-output.txt

      # ====================
      #       Clippy
      # ====================

      # - name: Run clippy all features
      #   id: clippy
      #   continue-on-error: true
      #   shell: 'nix develop -c bash -e {0}'
      #   run: cargo clippy --all-features -- -D warnings 2>&1 | tee clippy-output.txt

      # # ====================
      # #       Docs
      # # ====================

      # - name: Documentation
      #   id: docs
      #   continue-on-error: true
      #   env:
      #     RUSTDOCFLAGS: -Dwarnings
      #   run: cargo doc --all-features --no-deps --document-private-items 2>&1 | tee docs-output.txt

      # # ====================
      # #     MSRV Check
      # # ====================

      # - name: Run cargo-msrv
      #   id: msrv
      #   continue-on-error: true
      #   run: /bin/bash ./scripts/ci/msrv.sh 2>&1 | tee msrv-output.txt

      # # ====================
      # #    Useless deps
      # # ====================

      # - name: Run cargo-machete
      #   id: dependancies
      #   continue-on-error: true
      #   run: /bin/bash ./scripts/ci/udeps.sh 2>&1 | tee dependancies-output.txt

      # # ====================
      # #    Min versions
      # # ====================

      # - name: Install nightly toolchain for minimum_versions
      #   uses: dtolnay/rust-toolchain@nightly

      # - uses: taiki-e/install-action@cargo-hack

      # - uses: taiki-e/install-action@cargo-minimal-versions

      # - name: Run cargo-minimal-versions
      #   id: minimum_versions
      #   continue-on-error: true
      #   run: /bin/bash ./scripts/ci/minimum_versions.sh 2>&1 | tee minimum-versions-output.txt


      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const script = require('./scripts/ci-comment-on-failure.js')
            script({github, context, octokit, fs})
      


  stable_tests:
    env: 
      SQLX_OFFLINE: true
    runs-on: ${{ matrix.os }}
    needs: checks
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2
        with: 
          key: "(${{ matrix.os }})"

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
        
      - name: Run tests
        run: cargo nextest run --all-features